/**
 * Keyless end-to-end proof of the real ingestion pipeline (OCR → parse →
 * classify → addresses) against the synthetic fixtures in
 * tests/fixtures/pdfs/ (generated by scripts/generate-fixtures.mts).
 *
 * Runs with OCR_PROVIDER=tesseract (free, local, no API key) so this suite
 * works in any environment with no secrets configured. Tesseract introduces
 * real OCR noise, so numeric assertions use a tolerant ±15% band rather than
 * exact equality — see docs comment on `expectWithinPct`.
 *
 * TESSERACT_SCALE / TESSERACT_COL_GAP_FACTOR are raised above their .env.example
 * defaults (2 / 1.2) for these specific fixtures' font metrics — this is the
 * documented, config-driven tuning knob for "tables come out misaligned"
 * (see .env.example), not a code change. Determined empirically against the
 * real reconstructor; see tests/fixtures/pdfs/README.md for what was found.
 *
 * OCR_CACHE_ENABLED is off: the cache key (caching.extractor.ts) is keyed on
 * provider + `ocr.model` — the tesseract engine never varies `ocr.model`, so a
 * prior run with different tuning (scale/col-gap) would silently serve a STALE
 * cached result. Disabling cache for this suite avoids that risk; each run
 * exercises the real OCR pipeline (this IS the point of the suite).
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import type { Item, PackingCategory } from "@/lib/packing/packing.types";
import type { IngestionResult } from "@/lib/ingestion/ingestion.service";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(__dirname, "..", "fixtures", "pdfs");

beforeAll(() => {
  // Set BEFORE any getConfig() call — env.ts lazily builds + caches its config
  // on first read, so this is safe regardless of import order.
  process.env.OCR_PROVIDER = "tesseract";
  process.env.OCR_CACHE_ENABLED = "false";
  process.env.TESSERACT_SCALE = "3";
  process.env.TESSERACT_COL_GAP_FACTOR = "3.0";
  process.env.LOG_LEVEL = process.env.LOG_LEVEL ?? "warn";
});

async function ingestFixture(name: string): Promise<IngestionResult> {
  // Imported lazily, after beforeAll has set the env vars the config module reads.
  const { ingestPdf } = await import("@/lib/ingestion/ingestion.service");
  const bytes = new Uint8Array(await readFile(join(FIXTURES_DIR, name)));
  return ingestPdf({
    bytes,
    mimeType: "application/pdf",
    filename: name,
    requestId: `e2e-${name}`,
  });
}

/** Tolerant numeric check — Tesseract noise on a synthetic-but-real render, not exact OCR. */
function expectWithinPct(actual: number, expected: number, pct = 0.15, label = ""): void {
  const diff = Math.abs(actual - expected);
  const bound = expected * pct;
  expect(diff, `${label}: expected ~${expected} (±${pct * 100}%), got ${actual}`).toBeLessThanOrEqual(bound);
}

function byCategory(items: readonly Item[], category: PackingCategory): Item[] {
  return items.filter((i) => i.category === category);
}

describe("ingestion e2e (tesseract, keyless)", () => {
  it("06-col-cm — clean 6-col cm table, 5 items, varied categories", async () => {
    const result = await ingestFixture("06-col-cm.pdf");
    expect(result.provider).toBe("tesseract");
    expect(result.classification.items).toHaveLength(5);

    const { assembleItems } = await import("@/lib/packing/item-assembler");
    const { loadColumnMap } = await import("@/lib/packing/column-map");
    const { loadStackabilityMatrix } = await import("@/lib/packing/stackability");
    const items = await assembleItems({
      doc: result.document,
      classification: result.classification,
      columnMap: await loadColumnMap(),
      matrix: await loadStackabilityMatrix(),
    });

    expect(items).toHaveLength(5);
    const expected: Array<{ category: PackingCategory; l: number; h: number; weightKg: number }> = [
      { category: "heavy-material", l: 3.0, h: 0.25, weightKg: 200 }, // Steel Beam
      { category: "glass-panel", l: 1.0, h: 1.5, weightKg: 90 }, // Glass Panel
      { category: "light-industrial", l: 2.0, h: 0.1, weightKg: 8 }, // PVC Conduit
      { category: "heavy-material", l: 2.5, h: 0.15, weightKg: 45 }, // Aluminum Channel
      { category: "appliance", l: 0.9, h: 0.6, weightKg: 8 }, // TV Monitor
    ];
    items.forEach((item, i) => {
      const exp = expected[i]!;
      expect(item.category, `item[${i}] category`).toBe(exp.category);
      expect(item.dimensions, `item[${i}] dimensions`).not.toBeNull();
      expectWithinPct(item.dimensions!.l, exp.l, 0.15, `item[${i}] length`);
      expectWithinPct(item.dimensions!.h, exp.h, 0.15, `item[${i}] height`);
      expect(item.quantity, `item[${i}] quantity`).toBe(1);
    });
  });

  it("11-col-metre — clean 11-col metre table, explicit Quantity + Depth", async () => {
    const result = await ingestFixture("11-col-metre.pdf");
    expect(result.classification.items).toHaveLength(5);

    const { assembleItems } = await import("@/lib/packing/item-assembler");
    const { loadColumnMap } = await import("@/lib/packing/column-map");
    const { loadStackabilityMatrix } = await import("@/lib/packing/stackability");
    const items = await assembleItems({
      doc: result.document,
      classification: result.classification,
      columnMap: await loadColumnMap(),
      matrix: await loadStackabilityMatrix(),
    });

    expect(items).toHaveLength(5);
    const expected = [
      { category: "heavy-material" as const, l: 0.9, h: 2.0, w: 0.6, weightKg: 25, quantity: 4 },
      { category: "glass-panel" as const, l: 0.8, h: 1.9, w: 0.1, weightKg: 22, quantity: 2 },
      { category: "light-industrial" as const, l: 1.5, h: 0.3, w: 0.3, weightKg: 6, quantity: 10 },
      { category: "heavy-material" as const, l: 0.5, h: 2.5, w: 0.1, weightKg: 12, quantity: 3 },
      { category: "appliance" as const, l: 0.3, h: 0.4, w: 0.3, weightKg: 3, quantity: 6 },
    ];
    items.forEach((item, i) => {
      const exp = expected[i]!;
      expect(item.category, `item[${i}] category`).toBe(exp.category);
      expect(item.dimensions, `item[${i}] dimensions`).not.toBeNull();
      expectWithinPct(item.dimensions!.l, exp.l, 0.15, `item[${i}] length`);
      expectWithinPct(item.dimensions!.h, exp.h, 0.15, `item[${i}] height`);
      expectWithinPct(item.dimensions!.w, exp.w, 0.15, `item[${i}] depth`);
      expectWithinPct(item.weightKg, exp.weightKg, 0.15, `item[${i}] weight`);
      expect(item.quantity, `item[${i}] quantity`).toBe(exp.quantity);
    });
  });

  it("multi-page — 6-col table spanning 2 pages, header repeated", async () => {
    const result = await ingestFixture("multi-page.pdf");
    expect(result.document.pageCount).toBe(2);
    expect(result.document.tableCount).toBe(2);
    expect(result.classification.items).toHaveLength(6);

    const { assembleItems } = await import("@/lib/packing/item-assembler");
    const { loadColumnMap } = await import("@/lib/packing/column-map");
    const { loadStackabilityMatrix } = await import("@/lib/packing/stackability");
    const items = await assembleItems({
      doc: result.document,
      classification: result.classification,
      columnMap: await loadColumnMap(),
      matrix: await loadStackabilityMatrix(),
    });

    expect(items).toHaveLength(6);
    expect(items.every((i) => i.dimensions !== null)).toBe(true);
    // 3 heavy-material (Beam, Channel, Pillar) + 1 glass-panel + 1 light-industrial + 1 appliance.
    expect(byCategory(items, "heavy-material")).toHaveLength(3);
    expect(byCategory(items, "glass-panel")).toHaveLength(1);
    expect(byCategory(items, "light-industrial")).toHaveLength(1);
    expect(byCategory(items, "appliance")).toHaveLength(1);
  });

  it("missing-dims — rows with blank H/W parse to dimensions:null, the rest valid", async () => {
    const result = await ingestFixture("missing-dims.pdf");
    expect(result.classification.items).toHaveLength(5);

    const { assembleItems } = await import("@/lib/packing/item-assembler");
    const { loadColumnMap } = await import("@/lib/packing/column-map");
    const { loadStackabilityMatrix } = await import("@/lib/packing/stackability");
    const items = await assembleItems({
      doc: result.document,
      classification: result.classification,
      columnMap: await loadColumnMap(),
      matrix: await loadStackabilityMatrix(),
    });

    expect(items).toHaveLength(5);
    // Row 2 (Glass Panel, blank Width) and row 4 (Aluminum Channel, blank Height) → null.
    expect(items[1]!.dimensions, "Glass Panel (blank width)").toBeNull();
    expect(items[3]!.dimensions, "Aluminum Channel (blank height)").toBeNull();
    // Rows 1, 3, 5 stay valid.
    for (const i of [0, 2, 4]) {
      expect(items[i]!.dimensions, `item[${i}] dimensions`).not.toBeNull();
    }
    expect(items[0]!.category).toBe("heavy-material");
    expect(items[2]!.category).toBe("light-industrial");
    expect(items[4]!.category).toBe("appliance");
  });

  it("mixed-units — one cm table + one metre table, per-table unit detection", async () => {
    const result = await ingestFixture("mixed-units.pdf");
    expect(result.document.tableCount).toBe(2);

    const { assembleItems } = await import("@/lib/packing/item-assembler");
    const { loadColumnMap } = await import("@/lib/packing/column-map");
    const { loadStackabilityMatrix } = await import("@/lib/packing/stackability");
    const items = await assembleItems({
      doc: result.document,
      classification: result.classification,
      columnMap: await loadColumnMap(),
      matrix: await loadStackabilityMatrix(),
    });

    expect(items).toHaveLength(4);
    // cm table (authored 20cm/300cm, 100cm/80cm) must land at METRE scale, not raw cm values.
    expectWithinPct(items[0]!.dimensions!.h, 0.2, 0.15, "cm-table Steel Beam height");
    expectWithinPct(items[0]!.dimensions!.l, 3.0, 0.15, "cm-table Steel Beam length");
    expectWithinPct(items[1]!.dimensions!.h, 1.0, 0.15, "cm-table Glass Panel height");
    expectWithinPct(items[1]!.dimensions!.l, 0.8, 0.15, "cm-table Glass Panel length");
    // metre table (authored already in metres) must NOT be re-scaled.
    expectWithinPct(items[2]!.dimensions!.h, 1.0, 0.15, "m-table Aluminum Channel height");
    expectWithinPct(items[2]!.dimensions!.l, 0.5, 0.15, "m-table Aluminum Channel length");
    expect(items[2]!.quantity).toBe(2);
    expectWithinPct(items[3]!.dimensions!.h, 0.2, 0.15, "m-table PVC Conduit height");
    expectWithinPct(items[3]!.dimensions!.l, 1.0, 0.15, "m-table PVC Conduit length");
    expect(items[3]!.quantity).toBe(5);
  });

  it("quantity-variants — plain int, decimal-with-floor, zero-padded quantities", async () => {
    const result = await ingestFixture("quantity-variants.pdf");

    const { assembleItems } = await import("@/lib/packing/item-assembler");
    const { loadColumnMap } = await import("@/lib/packing/column-map");
    const { loadStackabilityMatrix } = await import("@/lib/packing/stackability");
    const items = await assembleItems({
      doc: result.document,
      classification: result.classification,
      columnMap: await loadColumnMap(),
      matrix: await loadStackabilityMatrix(),
    });

    expect(items).toHaveLength(3);
    expect(items[0]!.quantity, "plain int \"5\"").toBe(5);
    expect(items[1]!.quantity, "decimal-with-floor \"3.0\"").toBe(3);
    expect(items[2]!.quantity, "zero-padded \"08\"").toBe(8);
  });

  it("addresses-collect-deliver — collection + delivery UK postcodes detected", async () => {
    const result = await ingestFixture("addresses-collect-deliver.pdf");
    expect(result.classification.items.length).toBeGreaterThanOrEqual(3);

    expect(result.addresses.pickup, "pickup address").not.toBeNull();
    expect(result.addresses.pickup).toContain("B33 8TH");
    expect(result.addresses.drops.some((d) => d.includes("M1 1AE")), "delivery address").toBe(true);
  });

  it("groupage-multidrop — one collection + 3 delivery postcodes", async () => {
    const result = await ingestFixture("groupage-multidrop.pdf");

    expect(result.addresses.pickup).toContain("CV1 1AA");
    expect(result.addresses.drops.length).toBeGreaterThanOrEqual(3);
    expect(result.addresses.drops.some((d) => d.includes("M1 1AE"))).toBe(true);
    expect(result.addresses.drops.some((d) => d.includes("LS1 4DY"))).toBe(true);
    expect(result.addresses.drops.some((d) => d.includes("B33 8TH"))).toBe(true);
  });

  it("junk-rows — totals row, blank row, and a SUBTOTAL banner don't crash or pollute", async () => {
    const result = await ingestFixture("junk-rows.pdf");

    const { assembleItems } = await import("@/lib/packing/item-assembler");
    const { loadColumnMap } = await import("@/lib/packing/column-map");
    const { loadStackabilityMatrix } = await import("@/lib/packing/stackability");
    const items = await assembleItems({
      doc: result.document,
      classification: result.classification,
      columnMap: await loadColumnMap(),
      matrix: await loadStackabilityMatrix(),
    });

    // 5 real items, plus tolerance for a possible dimensionless "Total Weight" phantom row.
    expect(items.length).toBeGreaterThanOrEqual(5);
    expect(items.length).toBeLessThanOrEqual(6);
    expect(byCategory(items, "heavy-material").length).toBeGreaterThanOrEqual(2); // Beam + Channel
    expect(byCategory(items, "glass-panel").length).toBeGreaterThanOrEqual(1);
    expect(byCategory(items, "light-industrial").length).toBeGreaterThanOrEqual(1);
    expect(byCategory(items, "appliance").length).toBeGreaterThanOrEqual(1);
    // The "SUBTOTAL" banner must never surface as a real cargo item.
    expect(items.some((i) => i.name.toUpperCase().includes("SUBTOTAL"))).toBe(false);
  });

  it("rasterized-scan — image-only PDF (no text layer) still OCRs via the tesseract raster path", async () => {
    const result = await ingestFixture("rasterized-scan.pdf");
    expect(result.classification.items).toHaveLength(5);

    const { assembleItems } = await import("@/lib/packing/item-assembler");
    const { loadColumnMap } = await import("@/lib/packing/column-map");
    const { loadStackabilityMatrix } = await import("@/lib/packing/stackability");
    const items = await assembleItems({
      doc: result.document,
      classification: result.classification,
      columnMap: await loadColumnMap(),
      matrix: await loadStackabilityMatrix(),
    });

    expect(items).toHaveLength(5);
    expect(items.every((i) => i.dimensions !== null)).toBe(true);
    expect(byCategory(items, "heavy-material")).toHaveLength(2);
    expect(byCategory(items, "glass-panel")).toHaveLength(1);
    expect(byCategory(items, "light-industrial")).toHaveLength(1);
    expect(byCategory(items, "appliance")).toHaveLength(1);
  });
});
