/**
 * Renders a Quote / GroupageQuote into an email (subject + html + text). Pure — no
 * I/O, no provider knowledge — so it's testable independent of how the mail is sent.
 */
import type { Quote } from "@/types/api";
import type { GroupageQuote } from "@/lib/groupage/groupage.types";
import { smartGBP } from "@/lib/fmt";

export interface QuoteEmailContent {
  readonly subject: string;
  readonly html: string;
  readonly text: string;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function lineItemRows(items: readonly { label: string; amount: number }[]): string {
  return items
    .map(
      (i) =>
        `<tr><td style="padding:6px 0;color:#444;">${escapeHtml(i.label)}</td>` +
        `<td style="padding:6px 0;text-align:right;white-space:nowrap;">${smartGBP(i.amount)}</td></tr>`,
    )
    .join("");
}

function wrap(title: string, bodyHtml: string, totalLabel: string, companyName: string): string {
  return `<!doctype html>
<html><body style="font-family:Arial,Helvetica,sans-serif;color:#1a1a1a;max-width:560px;margin:0 auto;">
<h2 style="margin:0 0 4px;">${escapeHtml(title)}</h2>
${companyName ? `<p style="margin:0 0 20px;color:#666;font-size:13px;">Quote generated by ${escapeHtml(companyName)}.</p>` : ""}
${bodyHtml}
<p style="margin-top:24px;font-size:12px;color:#888;">${escapeHtml(totalLabel)}</p>
</body></html>`;
}

/** companyName is config.email.fromName — blank omits the tagline rather than guessing a brand. */
export function buildQuoteEmail(quote: Quote, companyName = ""): QuoteEmailContent {
  const isChain = (quote.route.legs?.length ?? 0) > 1;
  const routeLine = isChain
    ? `${quote.route.origin} → … → ${quote.route.destination} (${quote.route.legs!.length} legs, incl. return)`
    : `${quote.route.origin} → ${quote.route.destination}`;
  const miles = quote.route.distanceMiles.toFixed(1);

  const vansRows = quote.vans
    .map(
      (v, i) =>
        `<tr><td style="padding:6px 0;color:#444;">${i + 1}. ${escapeHtml(v.description)}</td>` +
        `<td style="padding:6px 0;text-align:right;white-space:nowrap;">${smartGBP(v.distanceCost)}</td></tr>`,
    )
    .join("");

  const html = wrap(
    "Your Removals Quote",
    `<table style="width:100%;border-collapse:collapse;font-size:14px;">
      <tr><td colspan="2" style="padding:0 0 12px;"><strong>Route:</strong> ${escapeHtml(routeLine)} (${miles} mi)</td></tr>
      <tr><td colspan="2" style="padding:8px 0 4px;border-top:1px solid #eee;font-weight:600;">Vehicles</td></tr>
      ${vansRows}
      <tr><td colspan="2" style="padding:8px 0 4px;border-top:1px solid #eee;font-weight:600;">Breakdown</td></tr>
      ${lineItemRows(quote.lineItems)}
      <tr><td style="padding:12px 0 0;font-weight:700;font-size:16px;border-top:2px solid #333;">Total</td>
          <td style="padding:12px 0 0;font-weight:700;font-size:16px;text-align:right;border-top:2px solid #333;">${smartGBP(quote.total)}</td></tr>
    </table>`,
    "This quote reflects the details submitted at the time of generation and may change if those details change.",
    companyName,
  );

  const text = [
    "Your Removals Quote",
    `Route: ${routeLine} (${miles} mi)`,
    "",
    "Vehicles:",
    ...quote.vans.map((v, i) => `  ${i + 1}. ${v.description} — ${smartGBP(v.distanceCost)}`),
    "",
    "Breakdown:",
    ...quote.lineItems.map((i) => `  ${i.label}: ${smartGBP(i.amount)}`),
    "",
    `Total: ${smartGBP(quote.total)}`,
  ].join("\n");

  return { subject: "Your Removals Quote", html, text };
}

/** companyName is config.email.fromName — blank omits the tagline rather than guessing a brand. */
export function buildGroupageQuoteEmail(quote: GroupageQuote, companyName = ""): QuoteEmailContent {
  const { originHub, destinationHub } = quote.path;
  const routeLine =
    originHub && destinationHub
      ? quote.path.isLocal
        ? `${originHub.name} (local)`
        : `${originHub.name} → ${destinationHub.name}`
      : `${quote.originPostcode} → ${quote.destinationPostcode} (direct — no hub)`;

  const html = wrap(
    "Your Shared-Truck (Groupage) Quote",
    `<table style="width:100%;border-collapse:collapse;font-size:14px;">
      <tr><td colspan="2" style="padding:0 0 12px;"><strong>Route:</strong> ${escapeHtml(routeLine)}</td></tr>
      <tr><td colspan="2" style="padding:0 0 12px;"><strong>Load:</strong> ${quote.demand.palletCount} pallets · ${quote.demand.footprints} pallet-spaces · ${quote.demand.weightKg} kg</td></tr>
      ${quote.eta ? `<tr><td colspan="2" style="padding:0 0 12px;"><strong>Committed delivery:</strong> ${escapeHtml(quote.eta)}</td></tr>` : ""}
      <tr><td colspan="2" style="padding:8px 0 4px;border-top:1px solid #eee;font-weight:600;">Breakdown</td></tr>
      ${lineItemRows(quote.lineItems)}
      <tr><td style="padding:12px 0 0;font-weight:700;font-size:16px;border-top:2px solid #333;">Total</td>
          <td style="padding:12px 0 0;font-weight:700;font-size:16px;text-align:right;border-top:2px solid #333;">${quote.currencySymbol}${quote.total.toFixed(2)}</td></tr>
    </table>`,
    "This quote reflects the details submitted at the time of generation and may change if those details change.",
    companyName,
  );

  const text = [
    "Your Shared-Truck (Groupage) Quote",
    `Route: ${routeLine}`,
    `Load: ${quote.demand.palletCount} pallets · ${quote.demand.footprints} pallet-spaces · ${quote.demand.weightKg} kg`,
    ...(quote.eta ? [`Committed delivery: ${quote.eta}`] : []),
    "",
    "Breakdown:",
    ...quote.lineItems.map((i) => `  ${i.label}: ${quote.currencySymbol}${i.amount.toFixed(2)}`),
    "",
    `Total: ${quote.currencySymbol}${quote.total.toFixed(2)}`,
  ].join("\n");

  return { subject: "Your Shared-Truck (Groupage) Quote", html, text };
}
